modified index.html and skeleton.css
js-tasks-ru/htmlcss-20220120_daria-m-kuntsevich pull request #6
Opened 2022-02-04 18:02 UTC by DKuntsevich

Modified index.html and skeleton.css files

2022-02-04 18:03 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-02-07 17:39 UTC, GSemikozov requested changes

2022-02-07 17:39 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    width: 579px;
лучше жестко не фиксировать ширину

2022-02-07 17:39 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    padding: 40px;
точно по дизайну?)

2022-02-07 17:39 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    width: 515px;
и здесь это точно будет лишним

2022-02-07 17:39 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.content {
поскольку здесь мы описываем компонент .skeleton, а не .content - правильным будет определить контент как элемент скелетона, например .skeleton__content. И тогда элементы внутри контент - .content__line -> .skeleton__line, .content__inner -> .skeleton__content-inner, .content__avatar -> .skeleton__avatar и тд

2022-02-08 22:03 UTC, GSemikozov requested changes

2022-02-08 22:03 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +  .skeleton__content {
это удалим (и из стилей, и из разметки) - лишний враппер + элемент используется в разметке на одном уровне с блоком, но - все элементы блока это обязательно его дочерние элементы (то есть вложенные)

2022-02-08 22:03 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.container {
перенесем в тег style станицы с решением задачи

2022-02-08 22:03 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +  .skeleton__content-line-text {
skeleton__content-line-text -> skeleton__line_text

2022-02-08 22:03 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +  .skeleton__line-short {
.skeleton__line-short -> .skeleton__line_short

2022-02-08 22:03 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +  .skeleton__line-long {
.skeleton__line-long -> .skeleton__line_long

2022-02-10 15:05 UTC, GSemikozov approved these changes

2022-02-10 15:05 UTC, merged

2022-02-12 17:32 UTC, DKuntsevich commented on 04-lection2/02-skeleton/skeleton.css
> +  .skeleton__content {
Убрала .skeleton__content отовсюду

2022-02-12 17:33 UTC, DKuntsevich commented on 04-lection2/02-skeleton/skeleton.css
> +.container {
Перенесла .container в тег style страницы

2022-02-12 17:35 UTC, DKuntsevich commented on 04-lection2/02-skeleton/skeleton.css
> +  .skeleton__content-line-text {
Поменяла имена данного класса и все аналогичные

2022-02-12 17:36 UTC, DKuntsevich commented on 04-lection2/02-skeleton/skeleton.css
> +.content {
Внесла все необходимые изменения

2022-02-12 17:37 UTC, DKuntsevich commented on 04-lection2/02-skeleton/skeleton.css
> +    width: 515px;
Убрала .skeleton__content как ненужный враппер

2022-02-12 17:38 UTC, DKuntsevich commented on 04-lection2/02-skeleton/skeleton.css
> +    padding: 40px;
Перепроверила, исправила

2022-02-12 17:38 UTC, DKuntsevich commented on 04-lection2/02-skeleton/skeleton.css
> +    width: 579px;
Убрала фиксированную ширину