Feature/solution6
js-tasks-ru/htmlcss-20220120_daria-m-kuntsevich pull request #7
Opened 2022-02-06 15:19 UTC by DKuntsevich

Solved the "histogram" task

2022-02-06 15:19 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-02-12 12:56 UTC, GSemikozov requested changes

2022-02-12 12:56 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +:root {
root всегда определяется в одном месте, для нас это main.css

2022-02-12 12:56 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    margin: 5% 7% 0% 7%;
здесь если уж и используем проценты для отступов, то - лучше эти общие для всех дочерних элементов блока отступы задать 1 раз на уровне блока - это будет общий отступ для всех элементов, причем это будет внутренний отступ - padding

2022-02-12 17:59 UTC, DKuntsevich commented on 04-lection2/01-histogram/histogram.css
> +:root {
Перенесла в main.css

2022-02-13 13:55 UTC, DKuntsevich commented on 04-lection2/01-histogram/histogram.css
> +    margin: 5% 7% 0% 7%;
Задала paddings для общего блока .histogram

2022-02-13 21:26 UTC, GSemikozov submitted a review, later dismissed

2022-02-13 21:26 UTC, jsru commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2022-02-14 11:26 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-02-14 11:28 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-02-14 11:57 UTC, GSemikozov approved these changes

2022-02-14 11:57 UTC, merged